### PR TITLE
Renaming marklogic-junit to marklogic-junit5

### PR DESCRIPTION
**Pull request by rjrudin**
This allows for marklogic-junit5 to be published under marklogic-community

### CODE REVIEW

**Comment by jamesagardner** [comment]
I'm a little hesitant to call it junit5, while it is convenient for avoiding the naming collision and makes sense today, I'd hate to have to rename the package whenever junit 6, 7, or 8 come along.

Though I don't have better suggestions right now.

**Comment by jamesagardner** [comment]
I did some brief research, it appears there was a 10-11 year latency between the introduce of JUnit 4, and JUnit 5.  So that's not a huge burden to rename some point in 2027+ if the current trend continues.

**Comment by hansenmc** [comment]
Is this in an attempt to get around publishing/ownership issues?

Need to be careful not to create too many variants/forks of the same library published. It can make it hard for people to figure out which one is the correct or actively maintained lib (rjrudin/ml-junit, rjrudin/marklogic-junit, marklogic-community/marklogic-junit5, etc)

**Comment by jamesagardner** [comment]
> Need to be careful not to create too many variants/forks of the same library published. It can make it hard for people to figure out which one is the correct or actively maintained lib (rjrudin/ml-junit, rjrudin/marklogic-junit, marklogic-community/marklogic-junit5, etc)

I agree, any suggestions?

**Comment by rjrudin** [comment]
I think we're fine on that front - rjrudin/ml-junit is JUnit4 and never went anywhere, and rjrudin/marklogic-junit only has a version 0.11.0 out there.

**Pull request merged**
